name: chat
description: "A new Flutter project with clean architecture & firebase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # Functional programming things
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.7
  # Service locator
  get_it: ^8.0.3

  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  email_validator: ^3.0.0
  cloud_firestore: ^5.6.2

  flutter_bloc: ^9.0.0

  internet_connection_checker: ^3.0.1
  # Local cache
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
