// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

//Firebase configuration file lib\firebase_options.dart generated successfully with the following Firebase apps:
//
// Platform  Firebase App Id
// web       1:788723699764:web:b5c63df596f3bfa3fc7a61
// android   1:788723699764:android:3e1967c872097712fc7a61
// ios       1:788723699764:ios:4372516bf1641b08fc7a61
// macos     1:788723699764:ios:4372516bf1641b08fc7a61
// windows   1:788723699764:web:9ba9e2f22c42415ffc7a61

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBONd1_wI5krT9yr55NaqpM8cu0ALAEdkk',
    appId: '1:788723699764:web:b5c63df596f3bfa3fc7a61',
    messagingSenderId: '788723699764',
    projectId: 'chat-app-rama',
    authDomain: 'chat-app-rama.firebaseapp.com',
    storageBucket: 'chat-app-rama.firebasestorage.app',
    measurementId: 'G-NJPQY819G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_-JWfpyqqnpee3YFxv7iL4Gls-gD-FOE',
    appId: '1:788723699764:android:3e1967c872097712fc7a61',
    messagingSenderId: '788723699764',
    projectId: 'chat-app-rama',
    storageBucket: 'chat-app-rama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnxD2SKRRdzirhcB6suxpw8jtq44SNtiM',
    appId: '1:788723699764:ios:4372516bf1641b08fc7a61',
    messagingSenderId: '788723699764',
    projectId: 'chat-app-rama',
    storageBucket: 'chat-app-rama.firebasestorage.app',
    androidClientId: '788723699764-c9oaam0nd9161i7huhbek2kdr95v83dr.apps.googleusercontent.com',
    iosClientId: '788723699764-4il4caeieh241o1irqj4oc4rqg3mp513.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnxD2SKRRdzirhcB6suxpw8jtq44SNtiM',
    appId: '1:788723699764:ios:4372516bf1641b08fc7a61',
    messagingSenderId: '788723699764',
    projectId: 'chat-app-rama',
    storageBucket: 'chat-app-rama.firebasestorage.app',
    androidClientId: '788723699764-c9oaam0nd9161i7huhbek2kdr95v83dr.apps.googleusercontent.com',
    iosClientId: '788723699764-4il4caeieh241o1irqj4oc4rqg3mp513.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBONd1_wI5krT9yr55NaqpM8cu0ALAEdkk',
    appId: '1:788723699764:web:9ba9e2f22c42415ffc7a61',
    messagingSenderId: '788723699764',
    projectId: 'chat-app-rama',
    authDomain: 'chat-app-rama.firebaseapp.com',
    storageBucket: 'chat-app-rama.firebasestorage.app',
    measurementId: 'G-2YPEFLT29H',
  );
}
